### ISSUE TITLE
Make buffer sizes configurable by user

### ISSUE THREAD

**Issue by dpkoch** [dpkoch/async_comm#1]
Do this by using a construct like
```
#ifndef ASYNC_COMM_READ_BUFFER_SIZE
    #define ASYNC_COMM_READ_BUFFER_SIZE 512
#endif
```
in `comm.h`, so that users can do something like
```
#define ASYNC_COMM_READ_BUFFER_SIZE 64
#include <async_comm/serial.h>
```
to redefine the buffer size.

**Comment by dpkoch** [comment]
Closed by f0447d4

**Comment by RonaldEnsing** [comment]
Why has the option to make buffer sizes configurable been removed later on [1]? I am working with UDP packets that exceed this size and I use `async_comm` as a library, which means I would need to modify the `async_comm` code in order to read the packets completely. I'd very much prefer if this is configurable and I can use the installed package without the need of cloning and modifying the `syn_comm` code.

In addition, it is not clear to me why the buffer size is set to (effectively) 1024*1024 for UDP [2]. Why not set [1] to 1024*1024 (1048576) and [2] to `socket_.set_option(udp::socket::receive_buffer_size(READ_BUFFER_SIZE)`?

[1] https://github.com/dpkoch/async_comm/blob/master/include/async_comm/comm.h#L143
[2] https://github.com/dpkoch/async_comm/blob/master/src/udp.cpp#L88

**Comment by dpkoch** [comment]
Hi @RonaldEnsing, thanks for reaching out! I've opened two new issues, #13 and #14, to continue the discussion on the points you've brought up here.
